facts = """"
INTRODUCTION
-The application concerns, firstly, the removal of the applicant, a Syrian national who had expressed his intention to seek asylum to the German authorities, from Germany to Greece under an administrative arrangement between the two countries. The applicant was removed on the day of his arrival. He alleged a violation by Germany of, in particular, Article 3 of the Convention. The application concerns, secondly and under Articles 3 and 5 §§ 1 and 4 of the Convention, the conditions and legality of the applicant’s subsequent detention in Greece as well as the judicial control of that detention’s legality.
THE FACTS
- The applicant was born in 1993. He was represented by Mr A. Konstantinou, Ms E. Koutsouraki and Mr V. Papadopoulos, lawyers practising in Athens.
- The Greek Government were represented by their Agent’s delegate, Mr K. Georgiadis, Senior Advisor at the State Legal Council. The German Government were represented by two of their agents, Mr H.-J. Behrens and Ms N. Wenzel, of the Federal Ministry of Justice.
- The facts of the case may be summarised as follows.
THE APPLICANT’S ARRIVAL IN GREECE ON THE FIRST OCCASION
- On 30 June 2018 the applicant, a Syrian national, arrived on Megisti island, in Greece. He was detained upon arrival.
- On 4 July 2018 the Greek authorities ordered his removal to Türkiye on the basis of an agreement concluded between the member States of the European Union and Türkiye on 18 March 2016 (“the EU-Türkiye Statement”), which provides for migrants to be returned from Greece to Türkiye under certain conditions when they arrive irregularly. The applicant’s detention for the purposes of deportation was ordered, and he remained in detention in the police department of Megisti until his transfer to Leros island on 14 July 2018.
- On 18 July 2018 the applicant lodged an asylum application with the Regional Asylum Office of Leros. A condition not to leave Leros island (a “geographical limitation”) was imposed on him (see paragraph 53 below). Execution of the removal order was suspended until the asylum or readmission procedure was completed.
- According to the applicant, he was exposed to substandard living conditions in the Leros Reception and Identification Centre, a reception and identification centre (a “hotspot”), owing to overcrowding and poor reception conditions, and he left Leros for that reason. He was subsequently unable to continue the asylum procedure, as applications for international protection submitted by applicants who were subject to a condition not to leave a given island could only be examined by the competent asylum authorities of the respective island.
- On 13 August 2018 the Greek Asylum Service discontinued the examination of the applicant’s asylum application, as he did not attend the asylum interview scheduled for that day.
- According to the applicant, he left Greece owing to the lack of effective access to international protection and his fear that he would be arrested, detained and returned to Leros.
THE APPLICANT’S ARRIVAL IN GERMANY AND HIS RETURN TO GREECE
The German Government’s version of events
- According to the German Government, the events unfolded as follows. On an unspecified date the applicant travelled to Hungary. On 4 September 2018 he attempted to enter Germany via Austria by bus. At about 5 a.m. he was stopped during a check carried out by officers of the German Federal Police in the immediate vicinity of the German-Austrian border, in the Rottal-Ost area on the BAB3, a German federal motorway. The applicant tried to identify himself using a Bulgarian identity card issued to a different person. A search of the police databases showed that the identity card had been reported stolen. The applicant told the officers that he had bought the identity card in Greece for 2,000 euros (EUR) from a person he did not know. The officers searched the applicant and found, among other things, a Syrian identity card, a certificate of arrival issued by the Greek authorities and handwritten notes about organisations in Germany which helped refugees. The applicant told the officers that he intended to travel to Dortmund, where his brother lived; his brother had already applied for asylum there.
- The applicant was placed under provisional arrest on suspicion of unauthorised entry, unlawful residence and misuse of identity papers. As a person subject to provisional arrest, the applicant was informed that he had the right to contact defence counsel and to notify a relative or a person of his choosing of his arrest at any time, and that he could request that a person translate and interpret for him. The order for his provisional arrest, including the above-mentioned information as to his rights, was given to the applicant in writing, in Arabic.
- The officers took the applicant to Passau police station for questioning. There, the applicant was informed about his rights again and he was given an Arabic-speaking interpreter. The applicant indicated his wish to apply for asylum in Germany and to live with his brother in Dortmund. He expressly refused to consent to the Syrian mission in Germany being notified of his arrest. While being questioned as an accused person, the applicant was informed that he was to be returned to Greece. When asked by the officers if he would make himself available for voluntary return, the applicant stated that he would.
- The applicant was further informed that he was being refused entry because he had presented forged travel documents and did not possess the documents which would have permitted him to enter and reside in Germany, and he was heard on these points in the presence of an interpreter. The written refusal of entry issued under the Schengen Borders Code contained information including an Arabic translation of instructions on the right of appeal, which stated that an objection to the order refusing entry could be lodged with the Munich police headquarters within one month following notification of the refusal. That written decision also stated that the applicant would be returned to Austria.
- The applicant was returned to Athens by plane at 7.20 p.m. that same day, that is, 4 September 2018, on the basis of the “Administrative Arrangement between the Ministry of Migration Policy of the Hellenic Republic and the Federal Ministry of the Interior, Building and Community of the Federal Republic of Germany on cooperation when refusing entry to persons seeking protection in the context of temporary checks at the internal German-Austrian border” concluded in 2018 (see paragraph 63 below, hereafter “the administrative arrangement between Germany and Greece”). The German police issued a “notification of refusal of entry” to the Greek authorities, which stated that the applicant had been apprehended during a check at the border between Germany and Austria while attempting to enter Germany, that he did not meet the conditions for entry, that he had expressed a desire for international protection and that the Eurodac database showed that he had applied for asylum in Leros on 18 July 2018 (see paragraph 7 above).
- Shortly before the applicant was due to depart for the airport, the German officers in charge became aware that the “written notice of refusal of entry issued under the Schengen Borders Code” (see paragraph 14 above) was not the correct document by which to refuse the applicant entry. Therefore, shortly before departing, the applicant was issued with a refusal of entry for asylum-seekers, which an officer orally explained to him in English. An Arabic-speaking interpreter was not available at the time. The order refusing him entry was based on section 18(2) point 2 of the Asylum Act (see paragraph 54 below) and stated that there were indications that Greece had a responsibility to take back the applicant, under Regulation (EU) No 604/2013 of the European Parliament and of the Council of 26 June 2013 establishing the criteria and mechanisms for determining the Member State responsible for examining an application for international protection lodged in one of the Member States by a third-country national or a stateless person (recast) (see paragraph 61 below; hereafter “the Dublin III Regulation”). The order had a notice of the right to appeal attached to it, which indicated that any action against the decision should be brought before the Munich Administrative Court within two weeks after it had been delivered (section 74(1) of the Asylum Act, see paragraph 54 below).
The applicant’s version of events
- The applicant’s version of events differs from the one provided by the Government on the following points. According to the applicant, during his questioning at the police station he stated that he wished to apply for asylum in Germany. He was never willing to consent to being returned to Greece from Germany, as proven by the fact that he expressed his wish to apply for asylum to the German authorities. The German police officers told him during the questioning that he would be returned to Greece in any event, on a voluntary basis or otherwise, and that his asylum application would not be registered in Germany. Indeed, his asylum application was never registered, contrary to Germany’s obligation under, inter alia, the 1951 Convention relating to the Status of Refugees (see paragraph 57 below; hereafter, “the 1951 Convention”) and European Union (EU) law. He was never assisted by a lawyer and could not have access to reliable legal information concerning his right to remain in German territory to have his asylum application registered and examined. He asked to consult a lawyer for the criminal proceedings, but for reasons unknown to him he was never put in touch with one.
- During his questioning as an accused at the police station, the applicant was informed of the initial decision to refuse him entry. He received contradictory information at this stage. He was initially informed orally that he had been refused entry and that he was to be returned to Greece. No information on his right to have access to a lawyer or on available legal remedies was provided during the questioning. A written decision on refusal of entry under the Schengen Borders Code was given to the applicant, together with an information note in Arabic regarding the refusal of entry. Unlike the oral information he had previously been given, the written information mentioned that he would be returned to Austria. The same document, informing him about his return to Austria, mentioned his right to lodge an appeal with the Munich police headquarters (see paragraph 14 above). No information on legal assistance was provided in this note.
- Arabic was the only language the applicant understood. For that reason, his questioning at the police station was in Arabic, with the assistance of an interpreter, and he was served with the initial refusal of entry decision based on the Schengen Borders Code in Arabic. The later decision on refusal of entry for asylum-seekers was not explained to him by any officer in any language, and the Government did not provide any document to the Court to show that that decision had been explained to him, even in English.
- According to the applicant, he remained in Germany for only a few hours, as he was arrested at 5.15 a.m. on 4 September 2018 and returned to Greece at 7.20 p.m. the same day. He was transferred several times during those hours. His mobile phone was confiscated and he was allowed to make one phone call. He called his brother, who did not pick up the call.
PROCEEDINGS IN GREECE FOLLOWING THE APPLICANT’S RETURN
- Upon his arrival at Athens Airport from Munich on 4 September 2018 (see paragraph 15 above), the applicant was arrested. He was placed in detention in the Attica Directorate for Foreigners for a maximum period of six months, with a view to executing the removal decision of 4 July 2018 (see paragraphs 6-7 above – decision no. 666297/1-a). That decision mentioned Laws nos. 3386/2005, 3907/2011 and 4375/2016 (see paragraphs 49 and 50 below) and stated, inter alia, that there was a risk of absconding, as the applicant had violated the conditions of stay in the country. It was added that the applicant lacked the necessary documents, that he was dangerous for the public order and that the decision of 4 July 2018 concerning his removal to Turkey (see paragraph 6 above) was pending.
- On 6 September 2018 the applicant lodged an application for the continuation of the asylum proceedings (see paragraphs 7 and 9 above).
- According to the Greek Government, on 10 September 2018 the applicant was transferred to the island of Leros, where he was placed in detention at the local police station. According to the applicant, this transfer took place on 9 September 2018.
- On 12 September 2018 the Asylum Service decided not to revoke the decision to discontinue the asylum proceedings (see paragraph 9 above). The applicant had five days to appeal against that decision, but did not do so. Therefore, the decision became final on 17 September 2018.
- According to the applicant, on 21 September 2018 he was transferred to the Leros Reception and Identification Centre, where he was accommodated in a container. A new asylum application was registered.
- According to the Greek Government, the applicant was detained at the police station in Leros. The Government submitted a document issued by the police director of the Dodecanese, which mentioned this. Whenever it was necessary in the context of the asylum proceedings, the applicant was transferred to the Leros Reception and Identification Centre.
- On 5 October 2018 the applicant lodged objections against his detention with the administrative tribunal of Rhodes. He described the conditions of his detention in detail, submitted that these conditions were contrary to Article 3 of the Convention and relied on the Court’s case-law on the matter. He added that his detention was illegal, as he was a Syrian asylumseeker acting in good faith and did not present a flight risk.
- On 9 and 11 October 2018 the applicant’s asylum interview took place. He was then transferred back to Leros police station.
- According to the applicant, on 11 October 2018 he was examined by a psychiatrist and was diagnosed as a person suffering from an “anxietydepressive disorder”; medication was prescribed.
- On 11 October 2018 the president of the administrative tribunal of Rhodes rejected the objections (see paragraph 27 above – judgment no. AP148/2018). He mainly considered that the fact that an asylum application was pending did not preclude the applicant’s removal, as this could take place after the completion of the asylum proceedings. He stated that detention was a necessary measure, and added that the applicant had not proved his allegations concerning the conditions of his detention or that he had a stable place of residence.
- On 12 October 2018 an expert from the European Asylum Support Office (“EASO”) identified the applicant as a person belonging to a vulnerable group (“persons with disabilities or suffering from an incurable or serious illness”) and concluded that he should be exempted from the relevant border procedure (see paragraph 52 below).
- On 14 November 2018 the applicant lodged new objections with the administrative tribunal of Rhodes. He described his conditions of detention in detail, stating that he had not had access to outdoor space and exercise for two months and that these conditions were contrary to Article 3 of the Convention; he relied on the Court’s case-law on the matter. The applicant added that he was a vulnerable person and that his state of health was deteriorating owing to his detention. He also complained that his detention was contrary to Article 5 § 1 of the Convention, mainly because he was an asylum-seeker and therefore his removal could not take place.
- On 16 November 2018 the president of the administrative tribunal of Rhodes rejected the objections (judgment no. AP170/2018). She considered that the applicant had previously left the island of Leros irregularly, had left the country, and had been arrested by the German authorities. He was therefore considered to be at risk of absconding. The president of the administrative tribunal of Rhodes further noted that the applicant’s state of health did not constitute a danger to his physical integrity or life, as he was being provided with medical care. She added that he had not proved his allegations concerning the conditions of his detention.
- On 21 November 2018 the Reception and Identification Service issued a note to the Asylum Service, informing the latter that the applicant had been identified as a person belonging to a vulnerable group (see paragraph 31 above). On 23 November 2018 the Asylum Service referred the applicant’s asylum application so that it could be examined by way of the regular procedure. On 27 November 2018 the applicant was released from detention.
- On 7 April 2020 the Greek authorities recognised the applicant as a refugee.
CONDITIONS OF THE APPLICANT’S DETENTION IN LEROS
The Greek Government’s version of events
- According to the Greek Government, Leros police station has capacity for six detainees, and five people in total were being detained at the material time. The detention facilities comprise two cells, two toilets and one shower, and the total surface area is 30 sq. m. The facilities are cleaned and detainees are fed. Detainees can walk and have access to entertainment in a special area of the police station.
The applicant’s version of events
- According to the applicant, from 9 to 21 September 2018 and from 11 October 2018 to 27 November 2018 he was held at Leros police station. He remained in his cell 24 hours a day during the whole period of his detention and never had access to outdoor space and exercise. Leros police station is still located in the same building that it was in at the time of the Greek Ombudsman’s visit in June 2015, when the Ombudsman established “the yard area is of a very small surface, and it is not suitable for any use” (see paragraph 73 below); nothing has changed since then. The applicant was not allowed to access his mobile phone, there was not enough natural light or ventilation, the cell was very damp, and there were no chairs or a table or a space for recreation or dining. He had no access to any recreational activity or communication with the outside world. There was a lack of personal hygiene items, and he did not receive his prescribed medication for a significant period of time.
- From 21 September to 11 October 2018 he was accommodated in a container, which was used as an informal police cell in Leros Reception and Identification Centre.
- Owing to the nature of the cells at the police station and the reception and identification centre, both facilities were to be used for short-term detention.
SUBSEQUENT PROCEEDINGS IN GERMANY
- Through a German lawyer, the applicant filed an action before the Regensburg Administrative Court on 9 November 2018. He sought an order annulling the refusal of entry dated 4 September 2018 (see paragraph 14 above) and obliging the competent German authorities to readmit him under the Dublin III Regulation, bring him back to Germany immediately and continue the asylum procedure there. The applicant applied for restitutio in integrum as regards the time-limit within which such an action must be brought – within two weeks after the delivery of the relevant decision (see section 74(1) of the Asylum Act, quoted in paragraph 54 below). He submitted that he had been prevented from lodging the action earlier: he was no longer in possession of the decision refusing him entry, he had been detained in Greece immediately upon his return from Germany and he was still in detention. He had been unable to contact lawyers in Germany earlier; any contact with his German lawyer required facilitation by the Greek Council for Refugees.
- By an order of 12 December 2018 the Regensburg Administrative Court referred the applicant’s action to the Munich Administrative Court.
- In their submissions in reply of 6 January 2019, the Federal Police sought to have the action dismissed as inadmissible, because the applicant had not challenged the impugned decision within two weeks after its delivery, as required by section 74(1) of the Asylum Act. As regards the application for restitutio in integrum, the Federal Police asserted that the applicant had not sufficiently substantiated his claim that he had been prevented from lodging the action earlier.
- As those proceedings were still pending when the present application was lodged with the Court and when the parties exchanged observations on its admissibility and merits, the Court subsequently asked the parties to provide additional information about them.
- According to the applicant, for years there was no progress in the proceedings before the Munich Administrative Court, even though his lawyer requested that they be accelerated. On 12 July 2021, nearly three years after initiating the proceedings, the applicant re-entered Germany on his own and applied for asylum there the following day. By a letter of 24 August 2021 his lawyer informed the Munich Administrative Court about this development and stated that there was no longer any need to rule on the applicant’s request for an order obliging the German authorities to readmit him to Germany. The applicant also submitted that he had a legitimate interest in obtaining a declaratory judgment finding that the decision refusing him entry and his removal to Greece had been unlawful. The applicant’s lawyer added that an oral hearing could be dispensed with if the Munich Administrative Court intended to follow the approach it had taken in proceedings for interim relief in another case, in which it had ruled that the removal of another individual on the basis of the administrative arrangement between Germany and Greece had been unlawful (decision of 4 May 2021, see paragraph 65 in fine below).
- By a decision of 30 June 2022 the Federal Office for Migration and Refugees granted the applicant subsidiary protection in Germany. Referring to the judgment of the Court of Justice of the European Union (CJEU) of 19 March 2019 in Ibrahim and Others (Joined Cases C-297/17, C-318/17, C319/17 and C-438/17, ECLI:EU:C:2019:219), in which the CJEU had found that Article 33, paragraph 2 (a) of Directive 2013/32/EU of the European Parliament and of the Council of 26 June 2013 on common procedures for granting and withdrawing international protection, had to be interpreted as precluding a Member State from exercising the option granted by that provision to reject an application for international protection as being inadmissible on the ground that the applicant had been previously granted international protection by another Member State, where the living conditions that the applicant could be expected to encounter as a beneficiary of international protection in that other Member State would expose him to a substantial risk of suffering inhuman or degrading treatment, the Federal Office for Migration and Refugees took the view that there was a real risk that the living conditions which the applicant could be expected to encounter as a beneficiary of international protection in Greece would expose him to inhuman or degrading treatment within the meaning of Article 3 of the Convention and Article 4 of the Charter of Fundamental Rights of the European Union (see paragraph 58 below). His asylum application in Germany could therefore not be rejected as inadmissible on the ground that the applicant had already been granted international protection in Greece (see paragraph 35 above).
- On 7 February 2023 the Munich Administrative Court requested information from the applicant about the state of the asylum proceedings. It subsequently scheduled an oral hearing for 16 March 2023.
- On 8 March 2023 the applicant’s lawyer informed the Munich Administrative Court that the applicant had been granted subsidiary protection in Germany in the meantime (see paragraph 45 above) and there was no longer any need to rule on his action. The lawyer proposed that the scheduled oral hearing be cancelled, as the applicant would not be present. In his submissions to the Court, the applicant explained that he could not afford to travel some 600 kilometres from Dortmund, where he lived, to Munich in order to attend the oral hearing. On 29 March 2023 the respondent authority agreed that there was no longer any need to rule on the action.
- By an order of 17 April 2023 the Munich Administrative Court discontinued the proceedings, in view of the parties having declared that there was no longer any need to rule on the applicant’s action. It ordered each of the parties to bear half of the costs. In this regard, it explained that on the basis of a summary examination, the applicant’s initial claim by which he had sought to have the decision refusing him entry quashed and to obtain authorisation to be readmitted to Germany appeared to be admissible and was probably well founded. In particular, the action appeared to have complied with the relevant time-limit, in view of the incorrect information provided to the applicant about the legal remedy to be pursued, given that the two decisions refusing him entry which had been served on him had contained wholly contradictory information in this regard. However, with regard to the applicant’s claims as subsequently amended, it was questionable whether he had had a legitimate interest in obtaining a declaratory judgment.
RELEVANT LEGAL FRAMEWORK AND PRACTICE
DOMESTIC LEGAL FRAMEWORK
Greek legal framework
- Articles 76 and 83 of Law no. 3386/2005, as in force at the material time, are reproduced, in so far as relevant, in Barjamaj v. Greece (no. 36657/11, § 17, 2 May 2013). Law no. 3907/2011, as in force at the material time, applied to aliens staying illegally on the Greek territory (Article 17); its Article 30, which set out the detention of aliens subject to removal proceedings, is summarised in J.R and Others v. Greece (no. 22696/16, § 30, 25 January 2018).
- Article 46(2) of Law no. 4375/2016, as in force at the material time, provided that an asylum-seeker who submitted an application for international protection while he was in detention according to the relevant provisions of laws no. 3386/2005 and 3907/2011 shall, exceptionally, remain in detention if this was considered necessary after an individual assessment upon the condition that no alternative, less coercive measures could be applied, for one of the following reasons: (i) in order to determine his identity or nationality; (ii) in order to determine those elements on which the application for international protection was based which could not be obtained otherwise, in particular when there was a risk of absconding of the asylum-seeker; (iii) when it was ascertained on the basis of objective criteria, including that he or she already had the opportunity to access the asylum procedure, that there were reasonable grounds to believe that the asylum-seeker was making the application for international protection merely in order to delay or frustrate the enforcement of a return decision, if it was probable that the enforcement of such a measure could be effected; (iv) when he or she represented a danger for national security or public order; (v) when there was a serious risk of absconding of the asylum-seeker.
- Article 47(4) of Law no. 4375/2016, as in force at the material time, provided that an alien, in respect of whom the competent authority decided to discontinue the examination of the application for international protection, had the right to request the continuation of the examination of his or her application within nine months from the date of the discontinuation decision. The individual could not be deported until a final decision on the application was rendered.
- Article 60(4) of Law no. 4375/2016, as in force at the material time, provided for a fast-track border procedure for persons applying for international protection at the border or in airport/port transit zones, or while they were in reception and identification centres, with vulnerable individuals being exempt from that procedure.
- In accordance with the national legislation applicable at the relevant time, the condition to remain on one of the Aegean islands was imposed automatically on applicants for international protection who entered Greek territory through the islands of Lesbos, Samos, Chios, Kos, Rhodes and Leros “for public interest reasons and in particular for the implementation of the EU-Türkiye Statement of 18/03/2016” (Decision no. 8269, Gov. Gazette B’- 1366/20.04.2018 of the Director of the Greek Asylum Service). Police Circular no. 1604/16/1195968, issued by the Directorate of the Greek Police in June 2016, regulates the administrative treatment of aliens on whom a condition not to leave a given island has been imposed, if they are found in another part of the mainland. In such cases, “the detention measure will be restored and efforts will be made to transfer [the alien] back to the island for detention/further management (readmission to Türkiye).”
German legal framework
- The relevant provisions of the Asylum Act read as follows:
Section 18
“(1)  Any foreign national making an asylum request to an authority responsible for police supervision of cross-border traffic (a border authority) shall immediately be referred to the competent reception centre, or, if that is not known, to the nearest [reception centre], for the purpose of registration.
(2)  The foreign national shall be refused entry if
...
2.  in accordance with European Community law or an international treaty, there are indications that another country is responsible for processing the asylum application, and proceedings to admit or readmit [the foreign national] have been initiated, ...
(3)  The foreign national shall be removed if the border authority finds him near the border immediately before or after [his] illegal entry, and if the conditions defined in subsection 2 apply.
...”
Section 74
“(1)  An action against decisions pursuant to this Act must be brought no later than two weeks after [such a] decision has been delivered; in cases where an application under section 80(5) of the Administrative Courts Act must be filed within one week (section 34a(2), first and third sentences, section 36(3), first and tenth sentences), the action must also be brought within one week.
...”
Section 75
“(1)  An action brought against decisions pursuant to this Act shall have suspensive effect only in cases under section 38(1) and section 73, 73b and 73c.
...”
- Section 80(5) of the Administrative Courts Act provides that the court dealing with the main proceedings may grant suspensive effect in cases concerning administrative appeals or actions to set aside an administrative act, where such an appeal or action does not have automatic suspensive effect. Section 123(1) of the same Act provides that the court may make an interim order in other cases.
- Section 32(1) of the Federal Constitutional Court Act provides that the Federal Constitutional Court may provisionally decide a matter by way of a preliminary injunction if this is urgently required to avert a severe disadvantage, to prevent imminent violence, or for some other important reason in the interest of the common good.
INTERNATIONAL LAW
- The relevant provisions of the 1951 Convention relating to the Status of Refugees have been reproduced in M.A. and Others v. Lithuania (no. 59793/17, § 51, 11 December 2018).
EUROPEAN UNION LAW AND MATERIAL
- Relevant provisions of the Charter of Fundamental Rights of the European Union have been summarised in M.A. and Others v. Lithuania (cited above, § 56).
- Relevant provisions of Regulation (EU) 2016/399 of the European Parliament and of the Council of 9 March 2016 on a Union Code on the rules governing the movement of persons across borders (“the Schengen Borders Code”) have been summarised in M.A. and Others v. Lithuania (cited above, § 57).
- The principle of mutual trust between the Member States, on which the Common European Asylum System is based, is of fundamental importance in EU law (see, for example, the judgment of the Court of Justice of the European Union in M.S. and Others v Minister for Justice and Equality, C-616/19, ECLI:EU:C:2020:1010, § 48, 10 December 2020).
- Regulation (EU) No 604/2013 of the European Parliament and of the Council of 26 June 2013 (“the Dublin III Regulation”) establishes the criteria and mechanisms for determining the Member State responsible for examining an application for international protection lodged in one of the Member States by a third-country national or a stateless person. The second and the third subparagraphs of Article 3(2) of the Dublin III Regulation provide:
“Where it is impossible to transfer an applicant to the Member State primarily designated as responsible because there are substantial grounds for believing that there are systemic flaws in the asylum procedure and in the reception conditions for applicants in that Member State, resulting in a risk of inhuman or degrading treatment within the meaning of Article 4 of the Charter of Fundamental Rights of the European Union, the determining Member State shall continue to examine the criteria set out in Chapter III in order to establish whether another Member State can be designated as responsible.
Where the transfer cannot be made pursuant to this paragraph to any Member State designated on the basis of the criteria set out in Chapter III or to the first Member State with which the application was lodged, the determining Member State shall become the Member State responsible.”
- Commission Recommendation (EU) 2016/2256 of 8 December 2016 addressed to the Member States on the resumption of transfers to Greece under Regulation (EU) No 604/2013 of the European Parliament and of the Council provided as follows in its recitals:
“(33)  The Commission acknowledges the important progress made by Greece, assisted by the Commission, EASO, Member States and international and nongovernmental organisations, to improve the functioning of the Greek asylum system since the M.S.S judgement in 2011. However, Greece is still facing a challenging situation in dealing with a large number of new asylum applicants, notably arising from the implementation of the pre-registration exercise, the continuing irregular arrivals of migrants, albeit at lower levels than before March 2016, and from its responsibilities under the implementation of the EU-Turkey Statement. There are moreover further important steps to be taken to remedy the remaining shortcomings in the Greek asylum system, in particular as regards the quality of reception facilities, the treatment of vulnerable applicants and the speed with which asylum applications are registered, lodged and examined in the two instances. In order to take account of the impact of this challenging situation on the overall functioning of the asylum system and in order to avoid placing an unsustainable burden on Greece, it is not yet possible to recommend a full resumption of Dublin transfers to Greece, although it remains the ultimate goal.
(34)  However, significant progress has been attained by Greece in putting in place the essential institutional and legal structures for a properly functioning asylum system and, there is a good prospect for a fully functioning asylum system being in place in the near future, once all the remaining shortcomings have been remedied, in particular as regards reception conditions and the treatment of vulnerable persons, including unaccompanied minors. It is, therefore, appropriate to recommend that transfers should resume gradually and on the basis of individual assurances, taking account of the capacities for reception and treatment of applications in conformity with relevant EU legislation, and taking account of the currently inadequate treatment of certain categories of persons, in particular vulnerable applicants, including unaccompanied minors. ...
...
(39)  The responsibility for deciding on the resumption of transfers in individual cases lies exclusively with Member States’ authorities under the control of the courts ...”
The Recommendation set out the following conditions and procedures relating to the resumption of transfers of asylum applicants to Greece under the Dublin III Regulation:
Scope
“(9)  The resumption of transfers should apply to asylum applicants who have entered Greece irregularly at external borders from 15 March 2017 onwards or to other persons for whom Greece is responsible under criteria other than Article 13 in Chapter III of Regulation (EU) No 604/2013 from that date gradually, following the capacities of reception and treatment of applicants in Greece conformity with Directives 2013/32/EU and 2013/33/EU. Vulnerable asylum applicants, including unaccompanied minors, should not be transferred to Greece for the time being.
Cooperation and individual assurances
(10)  Before transferring an applicant to Greece, Member State authorities are invited to cooperate closely with the Greek authorities in order to ensure that the conditions indicated in point 9 are met and in particular that the applicant will be received in a reception facility meeting the standards set out in EU law, in particular in the Reception Conditions Directive 2013/33/EU, that his or her application will be examined within the deadlines specified in the Asylum Procedures Directive 2013/32/EU, and that he or she will be treated in line with EU legislation in every other relevant respect. The Greek authorities are invited to fully cooperate in providing such assurances to the other Member States.”
The Recommendation and the relevant procedures were in use at the time the present application was lodged.
ADMINISTRATIVE ARRANGEMENT BETWEEN GERMANY AND GREECE
- The “Administrative Arrangement between the Ministry of Migration Policy of the Hellenic Republic and the Federal Ministry of the Interior, Building and Community of the Federal Republic of Germany on cooperation when refusing entry to persons seeking protection in the context of temporary checks at the internal German-Austrian border” (see paragraph 15 above) was concluded in 2018. In so far as relevant, it provided as follows:
“Part I: Cooperation when refusing entry to persons seeking protection in the context of temporary checks at the border between the Federal Republic of Germany and the Republic of Austria
1.  Content and scope
i.  This Administrative Arrangement covers the refusal of entry of persons in the framework of applicable national law if the following conditions are met:
a)  The person has been identified during a check at the border between the Federal Republic of Germany and the Republic of Austria and is to be refused entry.
b)  The person is not an unaccompanied minor at the time of identification.
c)  The person has expressed a desire for international protection.
d)  An entry in the Eurodac system (Category I Eurodac hit) indicates that the person has already requested protection in Greece, and such entry in the Eurodac system is dated from 1 July 2017 onwards.
ii.  In cases of subsection (i), the Greek Side will readmit the person after being notified that the German Side has refused entry.
...
3.  Implementing refusal of entry
i.  The German Side refusing entry may return the person by air only, at the Athens International Airport. The return should be initiated no more than 48 hours after the person has been apprehended at the border between the Federal Republic of Germany and the Republic of Austria, unless the Greek Side objects to the return within six hours from the automatic confirmation of receipt of notification, demonstrating why the conditions of Part I, No. 1 have not been met.
...”
- Seven persons were returned to Greece from Germany in 2018 on the basis of the administrative arrangement, and thirty-one persons were returned in 2019 (see Publication of the Federal Parliament no. 19/19887, 12 June 2020, p. 28). No individual assurances were given by the Greek authorities in respect of persons returned to Greece from Germany under that administrative arrangement (see Publication of the Federal Parliament no. 19/13857, cited above, pp. 13-14).
- Certain individuals who had been returned from Germany to Greece on the basis of and in the manner set out in the administrative arrangement between Germany and Greece initiated proceedings before German administrative courts and applied for interim relief. In essence, those individuals sought a ruling obliging the German authorities to transfer them back to Germany at the authorities’ expense and to allow them to enter Germany on a provisional basis and continue the asylum procedure there. In a decision of 9 May 2019 in case no. M 5 E 19.50027, the Munich Administrative Court dismissed the application for interim relief because the requested interim measure would anticipate the result of the main proceedings; in the circumstances of that case, it was not necessary to do so in order to avert unreasonable disadvantages for the applicant in question. In a decision of 8 August 2019 in case no. M 18 E 19.32238, the Munich Administrative Court granted the interim relief in so far as it ordered the German authorities to work towards transferring the applicant in question back to Germany at their own expense and to allow him to enter Germany on a provisional basis. It found that it appeared likely, based on a summary examination, that the applicant’s removal to Greece had been unlawful. Rejecting the application for interim relief – to the extent that it was granted – would entail unreasonable disadvantages for the applicant, who had substantiated his contention that he ran a significant risk of being removed from Greece to his country of origin, Afghanistan, in the near future, without an assessment of the merits of his asylum application in any European State. Notably, decisions taken by the Greek authorities indicated that the applicant was not considered a “Dublin returnee” or an asylum-seeker, but an alien whose presence was illegal. The proceedings in Greece concerning his previous asylum application had been discontinued as the applicant had abandoned the application; they could no longer be reopened. If he were to lodge another asylum application in Greece, such an application would presumably be treated as a subsequent application, and any appeals against the dismissal of such an application would not have suspensive effect. In a decision of 4 May 2021 in case no. M 22 E 21.30294, the Munich Administrative Court granted the interim relief and ordered the authorities to arrange for the applicant’s return from Greece to Germany, finding that his removal from Germany to Greece had been unlawful, inter alia, because the administrative arrangement did not render the Dublin III Regulation inapplicable and that a procedure under that Regulation would have had to be carried out.
MATERIAL CONCERNING THE SITUATION IN GREECE AT THE RELEVANT TIME
Execution of the Court’s judgment in M.S.S. v. Belgium and Greece
- The execution of the judgments in M.S.S. v. Belgium and Greece ([GC], no. 30696/09, ECHR 2011) and related cases was under the supervision of the Committee of Ministers of the Council of Europe when the present application was lodged. This is still the case, notably as regards the general measures to be taken by Greece in relation to the violations of Article 3 of the Convention found on account of the conditions of detention and living conditions of asylum-seekers, as well as the lack of an effective remedy against expulsion due to deficiencies in the asylum procedures. In 2017 the Committee of Ministers invited the Greek authorities to, inter alia, “improve conditions of detention in all detention facilities where irregular migrants and asylum seekers are detained, including by providing adequate health-care services” (CM/Del/Dec(2017)1288/H46-15, 7 June 2017, paragraph 4). In 2019 the Committee of Ministers “welcomed the ongoing efforts made by the Greek authorities ... to improve the national asylum system, and the notable increase in the overall rate of granting asylum; noting, however, with grave concern the increase of arrivals of third country nationals that could adversely affect the functioning of the asylum system and [was] the reason for the significant increase in the average time taken to register and process asylum applications, and the deficiencies of the asylum appeal procedure which [had] been reported by the Greek Ombudsman and expert NGOs” (CM/Del/Dec(2019)1348/H46-9, 6 June 2019, paragraphs 34). The Committee of Ministers further noted “with satisfaction that certain immigration detention facilities visited by the CPT in 2018 provided decent conditions, [but] expressed serious concern at the fact that a number of other immigration facilities and police stations seem[ed] to be below Convention standards”, and “invited the authorities to give effect to the recommendations made by the CPT and to improve the conditions in immigration detention facilities, including by providing adequate health-care services” (ibid., paragraphs 11 and 13).
The European Committee for the Prevention of Torture and Inhuman or Degrading Treatment or Punishment (“CPT”)
- The main findings of the CPT’s report of 26 September 2017 (CPT/Inf (2017) 25) in relation to reception and identification centres (socalled “hotspots”) on the Aegean islands are summarised in J.R. and Others v. Greece (cited above, §§ 54-57); the report was published following the CPT’s visits from 13 to 18 April 2016 and from 19 to 25 July 2016, shortly after the entry into force of the EU-Türkiye Statement (see paragraph 6 above). The same report described the conditions of immigration detention for adults in facilities other than reception and identification centres as very poor and inadequate in most of the places visited (paragraphs 51-61). In particular, the CPT observed that it had repeatedly been very critical of the conditions of detention found in many police and border guard stations, which did not offer suitable accommodation for lengthy periods of detention, and that foreign nationals continued to be detained in some police stations for many months (paragraphs 54-55).
- In its subsequent report of 19 February 2019 (CPT/Inf (2019) 4), following a visit from 10 to 19 April 2018, the CPT stated:
“70.  In the period since 2005, the CPT has paid particular attention to the issue of foreign nationals deprived of their liberty under aliens’ legislation in Greece and visited the country no less than nine times regarding this matter. Most recently, following its visits in April and July 2016, the CPT expressed its concern over the situation in the ‘hotspots’ on the Aegean islands and was highly critical of the continued and routine detention of foreign national children. The report also highlighted the totally inadequate conditions of detention in immigration detention facilities and in most of the police stations visited. ...
72.  ... [T]he CPT notes with concern that the use of immigration detention in Greece has significantly increased. ...
84.  The CPT has in its previous reports been very critical of the conditions of detention in police and border guard stations, and has repeatedly stressed that the detention facilities in most of them were totally unsuitable for holding detained persons for periods exceeding 24 hours. This remained the case for most police stations visited by the delegation in April 2018, and yet they are still being used to detain irregular migrants for prolonged periods. On the other hand, there are a few police and border guard stations that provide decent conditions of detention for short periods of stay. ...”
The United Nations High Commissioner for Refugees (“UNHCR”)
- In its “Recommendations for Greece in 2017” of February 2017, UNHCR stated, inter alia, “[a]lthough progress has been made, significant challenges related to reception, registration, asylum-processing, and solutions remain, giving raise to significant protection and safety risks” (DHDD(2017)435, p. 1). UNHCR called for a number of concrete actions, including actions to “[a]ddress the serious gaps on the islands immediately”, and stated “[k]eeping people on the islands in overcrowded, inadequate and insecure conditions is inhumane and must no longer be maintained” (ibid.).
- In a submission of 5 May 2017 to the Committee of Ministers in the context of supervision of the execution of the judgment in M.S.S. v. Belgium and Greece (DH-DD(2017)584 – see paragraph 66 above), UNHCR stated, inter alia, that there had been improvements in the asylum procedures in Greece since the delivery of that judgment in January 2011, but various challenges persisted (p. 1). Reception conditions on the islands, where all newly arrived third-country nationals who had arrived irregularly were initially placed following the EU-Türkiye Statement (see paragraph 6 above), remained very poor (p. 10). Moreover, UNHCR stated that “a high number of third-country nationals, including asylum seekers, mainly on the islands, continue to be held in detention facilities operated by the police directorates and in police stations, which are totally inappropriate for immigration detention” (p. 11). In that same submission, UNHCR stated:
“... [G]iven the public nature of this document, UNHCR takes note of the European Commission’s Recommendation addressed to Member States on the resumption of transfers to Greece under the Dublin Regulation ... which proposes that transfers could resume on the basis of individual assurances from the Greek authorities as to the availability of reception places and access to asylum procedures within a reasonable timeframe. UNHCR does not oppose the recommendation that transfers could resume on the basis of individual assurances from the Greek authorities, including the exclusion of vulnerable persons from the ambit of the recommendation.”
- In another submission of May 2019 to the Committee of Ministers (DH-DD(2019)600), UNHCR stated that the administrative detention of asylum-seekers was “no longer broadly applied as a systematic punitive and deterrence measure, as in the past ... However, conditions and procedural safeguards continue[d] to be problematic” (p. 6).
The UN Special Rapporteur on the human rights of migrants
- In his report of 24 April 2017 on his mission to Greece (A/HRC/35/25/Add.2), the UN Special Rapporteur on the human rights of migrants expressed various concerns about the fast-track border procedure (see paragraph 52 above), including the lack of an individual assessment of each case and the high risk of violating the non-refoulement principle (paragraph 82 of the report).
The Greek Ombudsman’s report following his visit to Leros in June 2015
- Following a visit to Leros island, the Greek Ombudsman published his findings. As regards Leros police station, it was established that the building was old and needed repair; it also needed to be painted and cleaned, especially the parts which served as the detention areas. The premises, which had been designed to host six people, had sustained much damage as a result of the number of people hosted over the years and were filthy, with cracks on the walls, dirty blankets on the floor, insufficient lighting and inappropriate toilet facilities. According to the Ombudsman, this situation created a danger for the health and safety of the migrants and possibly also for the policemen in charge. The detention areas were not suitable for hosting people, even temporarily. The yard was very small and not suitable for any purpose.
""",
conclusion = 'Holds that there has been a violation by Greece of the substantive limb of Article 3 of the Convention;'



senior_system_prompt = "You are expert legal lawyer with European Court of Human Rights (ECHR)."

senior_base_prompt = """
    you are expert legal lawyer and expert at ECHR legal cases.
    carefully use the given facts of a legal case and conclusion, then are asked to identify the arguments provided for justifying the application of legal norms to the specific facts of the case.

    To do so, you have acess to an assisstant that can help you answer the questions you want to ask to be able to do the task.
    Collect the information you need to do the task, and then provide the reasoning behind the court decision.

    please ask one question at a time and wait for the answer before asking the next question.
    use the following format:
    Question: the question you want to ask
    Final Answer: to provide the reasoning behind the court decision
"""

junior_system_prompt = "You are expert legal lawyer with European Court of Human Rights (ECHR)."

junior_base_prompt = f"""
    you are expert legal lawyer and expert at ECHR legal cases.
    You are helping a senior lawyer with coming up with the reasoning behind the court decision.
    You task is to answer the following question about the given legal case facts and conclusion.
    you can't reply with question.
    you can't ask for more information.

    your answer should start with "Answer:"
    
    read the facts and conclusion carefully and wait for questions from the senior lawyer to answer them.
    reply with 'Ready for the next question' when you are ready for the next question.

    The facts, conclusion, and the question are given by XML tags <FACTS></FACTS>, <CONCLUSION></CONCLUSION>, <QUESTION></QUESTION> as follows:

    <FACTS>
    {facts}
    </FACTS>

    <CONCLUSION>
    {conclusion}
    </CONCLUSION>
"""




